# Equity Daily Setup Scanner
# ===========================
# Scans equities for trading setups based on technical features.
#
# TRIGGERS:
# - After Equity Daily Features completes
# - Manual trigger
#
# OUTPUT: Writes setups to setup_signals table

name: Equity Daily Setup Scanner

on:
  # Run after features workflow completes
  workflow_run:
    workflows: ["Equity Daily Features"]
    types:
      - completed
  
  # Manual trigger
  workflow_dispatch:
    inputs:
      target_date:
        description: 'Target date (YYYY-MM-DD). Leave empty for latest available.'
        required: false
        type: string
      workers:
        description: 'Number of parallel workers'
        required: false
        default: '8'
        type: string

env:
  PYTHON_VERSION: '3.11'

jobs:
  scan-setups:
    name: Scan Equity Setups
    runs-on: ubuntu-latest
    # Only run if the triggering workflow succeeded (or if manually triggered)
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary pandas numpy
      
      - name: Run setup scanner
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "🔍 Starting Equity setup scanner"
          if [ -n "${{ github.event.inputs.target_date }}" ]; then
            echo "📅 Target date: ${{ github.event.inputs.target_date }}"
            python jobs/equity_daily_setup_scanner.py \
              --date ${{ github.event.inputs.target_date }} \
              --workers ${{ github.event.inputs.workers || '8' }}
          else
            echo "📅 Using latest available date"
            python jobs/equity_daily_setup_scanner.py \
              --workers ${{ github.event.inputs.workers || '8' }}
          fi
