name: Index/Commodity/ETF Daily OHLCV

on:
  # Run daily at 22:00 UTC (after US market close)
  schedule:
    - cron: '0 22 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      date:
        description: 'Target date (YYYY-MM-DD, leave empty for today)'
        required: false
        default: ''

jobs:
  ingest-ohlcv:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests psycopg2-binary

      - name: Run Index/Commodity/ETF OHLCV Ingestion
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: |
          # Build command with optional date argument
          CMD="python -m jobs.index_commodity_etf_daily_ohlcv"
          
          if [ -n "${{ github.event.inputs.date }}" ]; then
            CMD="$CMD --date ${{ github.event.inputs.date }}"
          fi
          
          echo "Running: $CMD"
          $CMD

      - name: Report Results
        if: always()
        run: |
          echo "Index/Commodity/ETF OHLCV ingestion completed"
          echo "Check the logs above for detailed results"
