# ETF/Index/Commodity AI Signals (Parallel E2B)
# ==============================================
# Processes ETFs, Indices, and Commodities using parallel E2B sandboxes with Gemini AI.
# Each sandbox handles a batch of assets for sector/macro analysis.
#
# TRIGGERS:
# - Manual dispatch only (due to cost)
#
# REQUIREMENTS:
# - E2B_API_KEY secret
# - DATABASE_URL secret
# - GEMINI_API_KEY secret

name: ETF/Index/Commodity AI Signals (Parallel E2B)

on:
  # Manual dispatch only
  workflow_dispatch:
    inputs:
      target_date:
        description: 'Target date (YYYY-MM-DD). Leave empty for today.'
        required: false
        type: string
      sandboxes:
        description: 'Number of E2B sandboxes to spawn (max 50)'
        required: false
        default: '10'
        type: string
      max_concurrent:
        description: 'Maximum concurrent sandboxes'
        required: false
        default: '10'
        type: string
      stagger_delay:
        description: 'Seconds between launching each sandbox'
        required: false
        default: '2'
        type: string
      model:
        description: 'Gemini model to use'
        required: false
        default: 'gemini-3-flash-preview'
        type: string

env:
  PYTHON_VERSION: '3.11'

jobs:
  parallel-ai-analysis:
    name: Parallel ETF/Index/Commodity AI Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install orchestrator dependencies
        run: |
          python -m pip install --upgrade pip
          pip install e2b-code-interpreter psycopg2-binary
      
      - name: Determine target date
        id: date
        run: |
          if [ -n "${{ github.event.inputs.target_date }}" ]; then
            echo "date=${{ github.event.inputs.target_date }}" >> $GITHUB_OUTPUT
          else
            echo "date=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT
          fi
      
      - name: Run parallel E2B orchestrator
        env:
          E2B_API_KEY: ${{ secrets.E2B_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "🚀 Starting parallel ETF/Index/Commodity AI analysis"
          echo "📅 Date: ${{ steps.date.outputs.date }}"
          echo "🔢 Sandboxes: ${{ github.event.inputs.sandboxes || '10' }}"
          echo "⚡ Max Concurrent: ${{ github.event.inputs.max_concurrent || '10' }}"
          echo "⏱️ Stagger Delay: ${{ github.event.inputs.stagger_delay || '2' }}s"
          echo ""
          
          python scripts/e2b_etf_orchestrator.py \
            --date ${{ steps.date.outputs.date }} \
            --model ${{ github.event.inputs.model || 'gemini-3-flash-preview' }} \
            --sandboxes ${{ github.event.inputs.sandboxes || '10' }} \
            --max-concurrent ${{ github.event.inputs.max_concurrent || '10' }} \
            --stagger-delay ${{ github.event.inputs.stagger_delay || '2' }}
      
      - name: Report completion
        if: success()
        run: |
          echo "✅ ETF/Index/Commodity AI analysis completed successfully"
          echo "Assets analyzed for sector/macro themes"
      
      - name: Report failure
        if: failure()
        run: |
          echo "❌ ETF/Index/Commodity AI analysis failed"
