#!/usr/bin/env python3
"""
Insert global tech stocks into the assets table.
Uses the global_tech_stocks.json file generated by fetch_global_tech_stocks.py
"""

import os
import json
import psycopg2
import psycopg2.extras
from datetime import datetime

# Database connection
DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://postgres:stratosbrainpostgresdbpw@db.wfogbaipiqootjrsprde.supabase.co:5432/postgres"
)

def get_db_connection():
    """Get database connection."""
    return psycopg2.connect(DATABASE_URL)

def load_stocks():
    """Load stocks from JSON file."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(script_dir, "global_tech_stocks.json")
    
    with open(json_path, "r") as f:
        return json.load(f)

def check_existing_symbols(conn, symbols):
    """Check which symbols already exist in the database."""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT symbol, fmp_symbol 
            FROM assets 
            WHERE symbol = ANY(%s) OR fmp_symbol = ANY(%s)
        """, (symbols, symbols))
        rows = cur.fetchall()
        existing = set()
        for row in rows:
            if row[0]:
                existing.add(row[0])
            if row[1]:
                existing.add(row[1])
        return existing

def insert_stocks(stocks, dry_run=False):
    """Insert stocks into the assets table."""
    conn = get_db_connection()
    
    try:
        # Get existing symbols
        symbols = [s["symbol"] for s in stocks]
        existing = check_existing_symbols(conn, symbols)
        
        print(f"Found {len(existing)} existing symbols in database")
        
        # Filter out existing stocks
        new_stocks = [s for s in stocks if s["symbol"] not in existing]
        print(f"Will insert {len(new_stocks)} new stocks")
        
        if dry_run:
            print("\nDry run - would insert:")
            for stock in new_stocks[:20]:
                print(f"  {stock['symbol']}: {stock['name']} ({stock['currency']})")
            if len(new_stocks) > 20:
                print(f"  ... and {len(new_stocks) - 20} more")
            return 0
        
        inserted = 0
        with conn.cursor() as cur:
            for stock in new_stocks:
                try:
                    cur.execute("""
                        INSERT INTO assets (
                            asset_type, symbol, name, sector, industry, 
                            exchange, currency, is_active, data_vendor, fmp_symbol
                        ) VALUES (
                            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                        )
                        ON CONFLICT (symbol, asset_type) DO UPDATE SET
                            name = EXCLUDED.name,
                            sector = EXCLUDED.sector,
                            industry = EXCLUDED.industry,
                            exchange = EXCLUDED.exchange,
                            currency = EXCLUDED.currency,
                            data_vendor = EXCLUDED.data_vendor,
                            fmp_symbol = EXCLUDED.fmp_symbol,
                            updated_at = now()
                        RETURNING asset_id
                    """, (
                        'global_equity',  # asset_type
                        stock['symbol'],
                        stock['name'],
                        stock.get('sector'),
                        stock.get('industry'),
                        stock.get('exchange'),
                        stock.get('currency', 'USD'),
                        True,  # is_active
                        'fmp',  # data_vendor
                        stock['symbol']  # fmp_symbol (same as symbol for FMP stocks)
                    ))
                    
                    result = cur.fetchone()
                    if result:
                        inserted += 1
                        print(f"Inserted: {stock['symbol']} - {stock['name'][:50]} (asset_id: {result[0]})")
                    
                except psycopg2.Error as e:
                    print(f"Error inserting {stock['symbol']}: {e}")
                    conn.rollback()
                    continue
            
            conn.commit()
        
        print(f"\nSuccessfully inserted {inserted} stocks")
        return inserted
        
    finally:
        conn.close()

def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Insert global tech stocks into database")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be inserted without actually inserting")
    parser.add_argument("--limit", type=int, default=200, help="Maximum number of stocks to insert")
    args = parser.parse_args()
    
    print("Loading global tech stocks...")
    stocks = load_stocks()
    print(f"Loaded {len(stocks)} stocks from JSON")
    
    # Limit if specified
    stocks = stocks[:args.limit]
    
    # Show currency breakdown
    currencies = {}
    for stock in stocks:
        curr = stock.get("currency", "Unknown")
        currencies[curr] = currencies.get(curr, 0) + 1
    
    print("\nCurrency breakdown:")
    for curr, count in sorted(currencies.items(), key=lambda x: -x[1]):
        print(f"  {curr}: {count}")
    
    print(f"\nInserting {len(stocks)} stocks...")
    inserted = insert_stocks(stocks, dry_run=args.dry_run)
    
    if not args.dry_run:
        print(f"\nDone! Inserted {inserted} new global tech stocks.")

if __name__ == "__main__":
    main()
