-- Migration: 013_company_chats.sql
-- Description: Create tables for company-specific AI chat sessions
-- This enables a Manus/ChatGPT-style interface with one chat per company

-- ============================================================================
-- COMPANY CHATS TABLE
-- ============================================================================
-- Stores one chat session per company (triggered on demand, not for all companies)

CREATE TABLE IF NOT EXISTS public.company_chats (
    chat_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Company identification (links to asset_id in existing tables)
    asset_id TEXT NOT NULL UNIQUE,  -- e.g., 'AAPL', 'BTC-USD'
    asset_type TEXT NOT NULL CHECK (asset_type IN ('equity', 'crypto')),
    
    -- Display metadata
    display_name TEXT NOT NULL,  -- e.g., 'Apple Inc.', 'Bitcoin'
    
    -- Chat configuration
    system_prompt TEXT,  -- Custom system prompt for this company chat
    model TEXT NOT NULL DEFAULT 'gemini-3-pro-preview',
    
    -- Tool configuration (which tools are enabled for this chat)
    tools_config JSONB NOT NULL DEFAULT '{
        "code_execution": true,
        "google_search": true,
        "function_calling": true
    }'::jsonb,
    
    -- Context: fundamentals and signals data injected into chat
    context_snapshot JSONB,  -- Latest fundamentals, signals, scores cached here
    context_updated_at TIMESTAMPTZ,
    
    -- Sandbox configuration (for code execution)
    sandbox_id TEXT,  -- External sandbox identifier if using isolated execution
    sandbox_status TEXT CHECK (sandbox_status IN ('active', 'hibernated', 'terminated')),
    
    -- Status
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_message_at TIMESTAMPTZ
);

-- Index for quick lookup by asset
CREATE INDEX IF NOT EXISTS idx_company_chats_asset_id 
ON public.company_chats (asset_id);

-- Index for listing active chats
CREATE INDEX IF NOT EXISTS idx_company_chats_status_updated 
ON public.company_chats (status, last_message_at DESC);

-- ============================================================================
-- CHAT MESSAGES TABLE
-- ============================================================================
-- Stores all messages in a chat session (user, assistant, tool calls, tool results)

CREATE TABLE IF NOT EXISTS public.chat_messages (
    message_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chat_id UUID NOT NULL REFERENCES public.company_chats(chat_id) ON DELETE CASCADE,
    
    -- Message ordering
    sequence_num INTEGER NOT NULL,  -- Order within the chat
    
    -- Message content
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'tool', 'system')),
    content TEXT,  -- Text content (may be null for tool calls)
    
    -- For tool calls (when assistant requests a tool)
    tool_calls JSONB,  -- Array of {id, name, arguments} for function calls
    
    -- For tool responses (when tool returns result)
    tool_call_id TEXT,  -- References the tool call this responds to
    tool_name TEXT,
    
    -- Code execution specific
    executable_code TEXT,  -- Code generated by model
    code_execution_result TEXT,  -- Output from code execution
    code_execution_error TEXT,  -- Error if code failed
    
    -- Search grounding specific
    grounding_metadata JSONB,  -- Search queries, sources, citations
    
    -- Generated images/files
    attachments JSONB,  -- Array of {type, url, mime_type, filename}
    
    -- Token tracking
    tokens_in INTEGER,
    tokens_out INTEGER,
    
    -- Metadata
    model TEXT,  -- Model used for this response
    latency_ms INTEGER,  -- Response time
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fetching messages in order
CREATE INDEX IF NOT EXISTS idx_chat_messages_chat_sequence 
ON public.chat_messages (chat_id, sequence_num ASC);

-- Index for recent messages
CREATE INDEX IF NOT EXISTS idx_chat_messages_chat_created 
ON public.chat_messages (chat_id, created_at DESC);

-- Unique constraint to prevent duplicate sequence numbers
CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_messages_unique_sequence 
ON public.chat_messages (chat_id, sequence_num);

-- ============================================================================
-- CHAT TOOL EXECUTIONS TABLE
-- ============================================================================
-- Detailed log of tool executions for audit and debugging

CREATE TABLE IF NOT EXISTS public.chat_tool_executions (
    execution_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id UUID NOT NULL REFERENCES public.chat_messages(message_id) ON DELETE CASCADE,
    chat_id UUID NOT NULL REFERENCES public.company_chats(chat_id) ON DELETE CASCADE,
    
    -- Tool identification
    tool_type TEXT NOT NULL CHECK (tool_type IN ('code_execution', 'google_search', 'function_call')),
    tool_name TEXT,  -- For function calls, the function name
    
    -- Execution details
    input_data JSONB,  -- Arguments/code passed to tool
    output_data JSONB,  -- Result from tool
    
    -- Status
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'success', 'error')),
    error_message TEXT,
    
    -- Timing
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    duration_ms INTEGER
);

-- Index for finding executions by message
CREATE INDEX IF NOT EXISTS idx_chat_tool_executions_message 
ON public.chat_tool_executions (message_id);

-- Index for finding executions by chat
CREATE INDEX IF NOT EXISTS idx_chat_tool_executions_chat 
ON public.chat_tool_executions (chat_id, started_at DESC);

-- ============================================================================
-- CHAT CONTEXT SNAPSHOTS TABLE
-- ============================================================================
-- Stores periodic snapshots of company data injected into chat context

CREATE TABLE IF NOT EXISTS public.chat_context_snapshots (
    snapshot_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chat_id UUID NOT NULL REFERENCES public.company_chats(chat_id) ON DELETE CASCADE,
    
    -- Snapshot content
    fundamentals JSONB,  -- Financial fundamentals data
    signals JSONB,  -- Current signal states
    scores JSONB,  -- Composite scores
    price_data JSONB,  -- Recent OHLCV data
    ai_reviews JSONB,  -- Recent AI reviews
    
    -- Source tracking
    as_of_date DATE,
    data_sources JSONB,  -- Which tables/APIs this data came from
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for finding latest snapshot per chat
CREATE INDEX IF NOT EXISTS idx_chat_context_snapshots_chat_date 
ON public.chat_context_snapshots (chat_id, created_at DESC);

-- ============================================================================
-- FUNCTION DECLARATIONS TABLE
-- ============================================================================
-- Stores custom function declarations available to the chat

CREATE TABLE IF NOT EXISTS public.chat_function_declarations (
    function_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Function definition
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    parameters JSONB NOT NULL,  -- JSON Schema for parameters
    
    -- Implementation
    implementation_type TEXT NOT NULL CHECK (implementation_type IN ('supabase_rpc', 'edge_function', 'external_api')),
    implementation_config JSONB NOT NULL,  -- How to call this function
    
    -- Access control
    is_active BOOLEAN NOT NULL DEFAULT true,
    allowed_asset_types TEXT[],  -- Which asset types can use this function
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Update company_chats.updated_at on any change
CREATE OR REPLACE FUNCTION update_company_chats_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_company_chats_updated_at ON public.company_chats;
CREATE TRIGGER trigger_company_chats_updated_at
    BEFORE UPDATE ON public.company_chats
    FOR EACH ROW
    EXECUTE FUNCTION update_company_chats_updated_at();

-- Update company_chats.last_message_at when new message is added
CREATE OR REPLACE FUNCTION update_chat_last_message_at()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.company_chats 
    SET last_message_at = NEW.created_at
    WHERE chat_id = NEW.chat_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_chat_last_message_at ON public.chat_messages;
CREATE TRIGGER trigger_chat_last_message_at
    AFTER INSERT ON public.chat_messages
    FOR EACH ROW
    EXECUTE FUNCTION update_chat_last_message_at();

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE public.company_chats IS 'One chat session per company for AI-powered research and analysis';
COMMENT ON TABLE public.chat_messages IS 'All messages in company chat sessions including tool calls and results';
COMMENT ON TABLE public.chat_tool_executions IS 'Detailed audit log of tool executions (code, search, functions)';
COMMENT ON TABLE public.chat_context_snapshots IS 'Periodic snapshots of company data injected into chat context';
COMMENT ON TABLE public.chat_function_declarations IS 'Custom function declarations available to chat for database/API access';

COMMENT ON COLUMN public.company_chats.asset_id IS 'Links to asset_id in dashboard views and other tables';
COMMENT ON COLUMN public.company_chats.tools_config IS 'JSON config for which tools are enabled: code_execution, google_search, function_calling';
COMMENT ON COLUMN public.company_chats.context_snapshot IS 'Cached fundamentals, signals, scores for quick context injection';
COMMENT ON COLUMN public.company_chats.sandbox_id IS 'External sandbox identifier for isolated code execution environment';

COMMENT ON COLUMN public.chat_messages.tool_calls IS 'Array of tool calls when assistant requests tools: [{id, name, arguments}]';
COMMENT ON COLUMN public.chat_messages.grounding_metadata IS 'Google Search grounding: queries, sources, citations';
COMMENT ON COLUMN public.chat_messages.attachments IS 'Generated files/images: [{type, url, mime_type, filename}]';
