-- Migration: 20260124_chat_diagrams.sql
-- Description: Create tables for AI-generated Excalidraw diagrams in Company Chat Studio
-- This enables NotebookLM-style diagram generation and editing with Excalidraw

-- ============================================================================
-- CHAT DIAGRAMS TABLE
-- ============================================================================
-- Stores Excalidraw diagrams generated by AI or created manually per chat

CREATE TABLE IF NOT EXISTS public.chat_diagrams (
    diagram_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Relationships
    chat_id UUID NOT NULL REFERENCES public.company_chats(chat_id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    
    -- Diagram metadata
    name TEXT NOT NULL,
    description TEXT,
    diagram_type TEXT, -- e.g., 'flowchart', 'org_chart', 'mind_map', 'relationship', 'timeline', 'custom'
    
    -- Excalidraw data
    excalidraw_data JSONB NOT NULL, -- Full Excalidraw scene JSON (elements, appState, files)
    
    -- Preview
    thumbnail_url TEXT, -- Optional S3/storage URL for preview image
    
    -- Generation metadata
    generation_prompt TEXT, -- The prompt used to generate this diagram
    generation_model TEXT, -- Model used for generation (e.g., 'gemini-3-pro-preview')
    is_ai_generated BOOLEAN NOT NULL DEFAULT false,
    
    -- Status
    status TEXT NOT NULL DEFAULT 'ready' CHECK (status IN ('generating', 'ready', 'error')),
    error_message TEXT,
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Index for fetching diagrams by chat
CREATE INDEX IF NOT EXISTS idx_chat_diagrams_chat_id 
ON public.chat_diagrams (chat_id);

-- Index for fetching diagrams by user
CREATE INDEX IF NOT EXISTS idx_chat_diagrams_user_id 
ON public.chat_diagrams (user_id);

-- Index for listing diagrams in order
CREATE INDEX IF NOT EXISTS idx_chat_diagrams_chat_created 
ON public.chat_diagrams (chat_id, created_at DESC);

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.chat_diagrams ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Users can only access their own diagrams
CREATE POLICY "Users can view their own diagrams" ON public.chat_diagrams
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own diagrams" ON public.chat_diagrams
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own diagrams" ON public.chat_diagrams
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own diagrams" ON public.chat_diagrams
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Update updated_at on any change
CREATE OR REPLACE FUNCTION update_chat_diagrams_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_chat_diagrams_updated_at ON public.chat_diagrams;
CREATE TRIGGER trigger_chat_diagrams_updated_at
    BEFORE UPDATE ON public.chat_diagrams
    FOR EACH ROW
    EXECUTE FUNCTION update_chat_diagrams_updated_at();

-- ============================================================================
-- STORAGE BUCKET FOR DIAGRAM THUMBNAILS
-- ============================================================================

-- Create storage bucket for diagram thumbnails (if not exists)
INSERT INTO storage.buckets (id, name, public)
VALUES ('chat-diagrams', 'chat-diagrams', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for chat-diagrams bucket
CREATE POLICY "Users can upload diagram thumbnails" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'chat-diagrams' AND
    auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "Anyone can view diagram thumbnails" ON storage.objects
  FOR SELECT USING (bucket_id = 'chat-diagrams');

CREATE POLICY "Users can delete their diagram thumbnails" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'chat-diagrams' AND
    auth.uid()::text = (storage.foldername(name))[1]
  );

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE public.chat_diagrams IS 'Excalidraw diagrams generated by AI or created manually in Company Chat Studio';
COMMENT ON COLUMN public.chat_diagrams.excalidraw_data IS 'Full Excalidraw scene JSON including elements, appState, and files';
COMMENT ON COLUMN public.chat_diagrams.diagram_type IS 'Type of diagram: flowchart, org_chart, mind_map, relationship, timeline, custom';
COMMENT ON COLUMN public.chat_diagrams.generation_prompt IS 'The user prompt that was used to generate this diagram via AI';
COMMENT ON COLUMN public.chat_diagrams.is_ai_generated IS 'Whether this diagram was generated by AI or created manually';
